name: 'dev_appserver'
version: 0.0.1
description: A web server built using the shelf package.
author: borysn xborysn@gmail.com
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  logging_handlers:
  rpc:
  dart_jwt:
